image:
  file: .gitpod.Dockerfile
privileged: true
tasks:
  - name: dockerd
    command: sudo dockerd
  - name: Compose
    command: docker-compose build
  - name: Google Cloud
    command: |
      gcloud auth login
      gcloud config set project spartan-impact-279014
      gcloud container clusters get-credentials my-first-cluster-1 --zone us-central1-c --project spartan-impact-279014
github:
  prebuilds:
    branches: true
    addBadge: true
ports:
  - port: 8080
    onOpen: ignore
  - port:  8081
    onOpen: ignore
vscode:
  extensions:
    - googlecloudtools.cloudcode@1.4.0:Gxy18d/QyadCa4CWSam8Jg==
    - vscoss.vscode-ansible@0.5.2:Mff9FZmh2X9uPnMB9kEzCA==