version: '3'

services:
  frontend:
    restart: on-failure
    build: src/frontend
    environment:
      ROCKET_ENV: production
    ports:
      - "8080:8080"
  backend:
    restart: on-failure
    build: src/backend
    ports:
      - "8081:8081"
