apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: minimal-microservice
build:
  artifacts:
  - image: microservice-backend
    context: src/backend
  - image: microservice-frontend
    context: src/frontend
deploy:
  kubectl:
    manifests:
    - kubernetes/backend.yml
    - kubernetes/frontend.yml
    - kubernetes/ingress.yml
