apiVersion: v1
kind: Service
metadata:
  name: microservice-frontend
spec:
  selector:
    app: microservice-frontend
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-frontend
spec:
  selector:
    matchLabels:
      app: microservice-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: microservice-frontend
    spec:
      containers:
        - name: microservice-frontend
          image: microservice-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
